version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./seed_database.sql:/docker-entrypoint-initdb.d/init.sql